services:
  - type: web
    name: meu-pit-backend # Substitua por um nome Ãºnico globalmente (ex: meu-site-livros-pit-bmarinho)
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    